const traitDescriptions = {
  Agreeableness: "A person's tendency to be compassionate and cooperative toward others.",
  Altruism:	"Find that helping others is genuinely rewarding, that doing things for others is a form of self-fulfillment rather than self-sacrifice.",
  Cooperation: "Dislike confrontation. They are perfectly willing to compromise or to deny their own needs to get along with others.",
  Modesty: "Are unassuming, rather self-effacing, and humble. However, they do not necessarily lack self-confidence or self-esteem.",
  Uncompromising: "See no need for pretense or manipulation when dealing with others and are therefore candid, frank, and genuine.",
  Sympathy: "Are tender-hearted and compassionate.",
  Trust: "Assume that most people are fundamentally fair, honest, and have good intentions. They take people at face value and are willing to forgive and forget.",

  Conscientiousness: "A person's tendency to act in an organized or thoughtful way.",
  "Achievement striving": "Try hard to achieve excellence. Their drive to be recognized as successful keeps them on track as they work hard to accomplish their goals.",
  Cautiousness: "Are disposed to think through possibilities carefully before acting.",
  Dutifulness: "Have a strong sense of duty and obligation.",
  Orderliness: "Are well-organized, tidy, and neat.",
  "Self-discipline": "Have the self-discipline, or 'will-power,' to persist at difficult or unpleasant tasks until they are completed.",
  "Self-efficacy": "Are confident in their ability to accomplish things.",

  Extraversion: "A person's tendency to seek stimulation in the company of others.",
  "Activity level": "Lead fast-paced and busy lives. They do things and move about quickly, energetically, and vigorously, and they are involved in many activities.",
  Assertiveness: "Like to take charge and direct the activities of others. They tend to be leaders in groups.",
  Cheerfulness: "Experience a range of positive feelings, including happiness, enthusiasm, optimism, and joy.",
  "Excitement-seeking":	"Are easily bored without high levels of stimulation.",
  Outgoing: "Genuinely like other people and openly demonstrate positive feelings toward others.",
  Gregariousness: "Find the company of others pleasantly stimulating and rewarding. They enjoy the excitement of crowds.",

  "Emotional range": "Also referred to as Neuroticism or Natural reactions, is the extent to which a person's emotions are sensitive to the individual's environment.",
  Fiery:	"Have a tendency to feel angry.",
  "Prone to worry":	"Often feel like something unpleasant, threatening, or dangerous is about to happen. The 'fight-or-flight' system of their brains is too easily and too often engaged.",
  Melancholy: "Tend to react more readily to life's ups and downs.",
  Immoderation: "Feel strong cravings and urges that they have difficulty resisting, even though they know that they are likely to regret them later. They tend to be oriented toward short-term pleasures and rewards rather than long-term consequences.",
  "Self-consciousness":	"Are sensitive about what others think of them. Their concerns about rejection and ridicule cause them to feel shy and uncomfortable around others; they are easily embarrassed.",
  "Susceptible to stress": "Have difficulty coping with stress. They experience panic, confusion, and helplessness when under pressure or when facing emergency situations.",

  Openness: "Or Open to Experience, is the extent to which a person is open to experiencing a variety of activities.",
  Adventurousness: "Are eager to try new activities and experience different things. They find familiarity and routine boring.",
  "Artistic interests":	"Love beauty, both in art and in nature. They become easily involved and absorbed in artistic and natural events. With intellect, this facet is one of the two most important, central aspects of this characteristic.",
  Emotionality: "Have good access to and awareness of their own feelings.",
  Imagination: "View the real world as often too plain and ordinary. They use fantasy not as an escape but as a way of creating for themselves a richer and more interesting inner-world.",
  Intellect: "Are intellectually curious and tend to think in symbols and abstractions. With artistic interests, this facet is one of the two most important, central aspects of this characteristic.",
  "Authority challenging": "Have a readiness to challenge authority, convention, and traditional values.",

  Excitement:	"Want to get out there and live life, have upbeat emotions, and want to have fun.",
  Harmony:	"Appreciate other people, their viewpoints, and their feelings.",
  Curiosity:	"Have a desire to discover, find out, and grow.",
  Ideal:	"Desire perfection and a sense of community.",
  Closeness:	"Relish being connected to family and setting up a home.",
  "Self-expression":	"Enjoy discovering and asserting their own identities.",
  Liberty:	"Have a desire for fashion and new things, as well as the need for escape.",
  Love:	"Enjoy social contact, whether one-to-one or one-to-many. Any brand that is involved in bringing people together taps this need.",
  Practicality:	"Have a desire to get the job done, a desire for skill and efficiency, which can include physical expression and experience.",
  Stability:	"Seek equivalence in the physical world. They favor the sensible, the tried and tested.",
  Challenge:	"Have an urge to achieve, to succeed, and to take on challenges.",
  Structure:	"Exhibit groundedness and a desire to hold things together. They need things to be well organized and under control.",

  "Self-transcendence": "Show concern for the welfare and interests of others.",
  Conservation:	"Emphasize self-restriction, order, and resistance to change.",
  Hedonism: "Seek pleasure and sensuous gratification for themselves.",
  "Self-enhancement": "Seek personal success for themselves.",
  "Openness to change": "Emphasize independent action, thought, and feeling, as well as a readiness for new experiences."
}

export default traitDescriptions;
